[package]
name = "flextide-node-registry"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
flextide-sdk = { path = "../sdk" }
